### ISSUE TITLE
Finalidade Base do Codigo

### ISSUE THREAD

**Issue by rspds** [cajubavictor/snake-killator#11]
Encontrei um jogo de snakes na internet, poderiamos nos basear nele para fazermos o código.
[Nokia Serpente 2](http://www.puffgames.com/snake/)
Concordam ou Discordam?

**Comment by dnloliveira1** [comment]
Será que existe um jogo oficial do snake, com manual e coisas do gênero? :smile:

**Comment by cajubavictor** [comment]
Valeeeu
